# Generated by Django 4.2.3 on 2023-10-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
